### ISSUE TITLE
Redesign CD pipeline page structure

### ISSUE THREAD

**Issue by NikolayMarusenko** [epam/edp-headlamp#11]
Currently the page with CD pipelines is quite overloaded with information, let's make an approach so that there is one combined page to understand the nesting structure of CD pipelines and also a page for each CD stage with a detailed display of data.

Acceptance Criteria:

- EDP user can open a separate page to display detailed information for each CD stages;
- CD pipelines page contain information about main pipeline structure, without detailed information about CD stages;

**Comment by callmevladik** [comment]
Implemented.
![image](https://github.com/epam/edp-headlamp/assets/42180137/2c830101-576a-41e4-ad6b-257a9d751444)
![image](https://github.com/epam/edp-headlamp/assets/42180137/9f38890d-f872-4440-b580-df86b832e246)
