### ISSUE TITLE
'No %s integration secrets found' message isn't displayed for some secrets on the configuration page

### ISSUE THREAD

**Issue by callmevladik** [epam/edp-headlamp#124]
STR:

Open EDP Configuration page
Delete external secret for any of (Nexus, SonarQube, Jira, DefectDojo, DependencyTrack, SSO, Registry)

ER: 'No %s integration secrets found' message should be displayed

AR: There is no message

**Comment by Serg1506** [comment]
![Screenshot_9](https://github.com/epam/edp-headlamp/assets/23012062/49ae2ef4-5f32-4c1c-aead-51061d5e108f)
