### ISSUE TITLE
Add namespaces unset dialog window, update notification logic

### ISSUE THREAD

**Issue by callmevladik** [epam/edp-headlamp#129]

**Comment by Serg1506** [comment]
![Screenshot_8](https://github.com/epam/edp-headlamp/assets/23012062/9feb02ac-93cb-490e-8465-9ecc3a761c17)
![Screenshot_9](https://github.com/epam/edp-headlamp/assets/23012062/bca65483-c3d2-42e7-ac71-e589973f5907)
