### ISSUE TITLE
Add visible checkbox in edpcomponent creation

### ISSUE THREAD

**Issue by callmevladik** [epam/edp-headlamp#132]

**Comment by Serg1506** [comment]
![Screenshot_14](https://github.com/epam/edp-headlamp/assets/23012062/17bf18cb-2f2f-424c-850d-f6acc169f6c4)
![Screenshot_15](https://github.com/epam/edp-headlamp/assets/23012062/232693cc-8cc2-4d31-b430-f853a9a6bdf8)
