### ISSUE TITLE
Update secret integration forms, update disabled edp links tooltips

### ISSUE THREAD

**Issue by callmevladik** [epam/edp-headlamp#138]
* Argo CD, Sonar, Nexus, DefectDojo, DependencyTrack forms are updated. Added ExternalURL field to manage specific EDPComponent resources together with the secret.
* Update disabled EDPComponent links tooltips. If EDPComponent's external url is included in secret integration, then it will have different link.
* Update EDPComponent form. Let user define only url and show checkbox for system edp components.

**Comment by Serg1506** [comment]
![Screenshot_35](https://github.com/epam/edp-headlamp/assets/23012062/7cbd2b25-395b-484b-a015-0307abf7dbe1)
![Screenshot_36](https://github.com/epam/edp-headlamp/assets/23012062/53040110-7649-4ebc-a375-c9c6b5680ee1)
