### ISSUE TITLE
Redesign environment details page

### ISSUE THREAD

**Issue by callmevladik** [epam/edp-headlamp#142]
Inspiration: https://codefresh.io/blog/introducing-the-worlds-first-dashboard-for-gitops-environments/ 

The environment page contains information:

General Overview. Get information from Argo Application(s) fields from labels:
labels:
app.edp.epam.com/app-name: demo
app.edp.epam.com/pipeline: demo     <- Filter by this field to group all applications for CDPipeline
app.edp.epam.com/stage: dev              <- Show applications for specific stage
use targetRevision (imageTag) to show versions
add argo application name.
Main Content Area:
Environment Overview:
Display a grid or card-based layout to represent each environment (e.g., development, staging, production).
Each card should show the environment name, a brief description, and the number of applications deployed.
Application Cards:
Within each environment card, display application cards.
Each application card should include the application name, version, health status, and synchronization status.
Use color-coded indicators (green for healthy, yellow for warnings, red for critical issues) for quick visual recognition.
Filter and Search:
Provide filters for namespaces, applications, and health status.
Include a search bar for users to quickly find specific applications or environments.
Detailed Application View:
Allow users to click on an application card to access a detailed view (right swap pannel)
(Under discussion)Show comprehensive information about the selected application, including labels, custom resources, and deployment details.
Environment Grid Cell:

Each environment grid cell represents a specific Kubernetes environment (e.g., Development, Staging, Production). The cell is designed to provide a quick overview of the environment's applications and their current status.

Environment Title:
At the top of the cell, prominently display the name of the environment (e.g., "Development," "Staging," "Production").
Environment Description (can be an  icon):
Below the title, include a brief description or metadata about the environment. This could include details such as the cluster name, location, or any relevant information to help users identify the context of the environment.
Applications Overview:
Use a card-based layout to showcase the applications deployed in that environment.
For each application, display key information:
Application Name:
Clearly state the name of the application.
Version:
Display the current version of the application.
Health Status:
Use color-coded indicators from Argo CD (green for healthy, yellow for warnings, red for critical issues) to represent the health status of each application.
Sync Status:
Indicate whether the application is in sync with the desired state (e.g., using icons like a checkmark for in sync and an alert symbol for out of sync).

**Comment by Serg1506** [comment]
![Screenshot_15](https://github.com/epam/edp-headlamp/assets/23012062/d4c20a64-9565-4751-a0d6-df3f00e7b9b0)
