### ISSUE TITLE
Steps from the finally block in a pipeline aren't displayed on the tree diagram

### ISSUE THREAD

**Issue by callmevladik** [epam/edp-headlamp#146]
STR:

Create any codebase and run the build pipeline
Open the tree diagram and compare stages with tekton

ER: The tree diagram contains all stages

AR: Steps from the finally block in a pipeline aren't displayed

**Comment by Serg1506** [comment]
![Screenshot_42](https://github.com/epam/edp-headlamp/assets/23012062/aeb6e782-af52-4045-8efa-5e597dfa805c)
![Screenshot_40](https://github.com/epam/edp-headlamp/assets/23012062/3e5e8db1-7c1d-4e0a-8fad-ffd1c18f08e5)
