### ISSUE TITLE
Update Jira integration similar to GitServer

### ISSUE THREAD

**Issue by callmevladik** [epam/edp-headlamp#150]
Now, if EDP is deployed without Jira integration it doesn't have JiraServer, as a result, added Jira secret won't be displayed on the configuration page without JiraServer. 

It is necessary to prohibit Jira integration without a Jira server on the configuration page.

Acceptance Criteria:

EDP Portal can manage Jira Server CR;
EDP Portal can manage Jira Server secret (ci-jira), align with VCS integration;

For text description contact with [Oleksandr Stepanov](https://jiraeu.epam.com/secure/ViewProfile.jspa?name=Oleksandr_Stepanov%40epam.com)

**Comment by Serg1506** [comment]
![Screenshot_3](https://github.com/epam/edp-headlamp/assets/23012062/6e813d32-d0af-4762-968d-bc87be91a86d)
