### ISSUE TITLE
Add deploy pipeline run list into stage page

### ISSUE THREAD

**Issue by callmevladik** [epam/edp-headlamp#151]
Acceptance criteria:

enable diagram tree like for CI part;

**Comment by Serg1506** [comment]
![Screenshot_33](https://github.com/epam/edp-headlamp/assets/23012062/1069396a-5980-4410-af0f-9cbd910573af)
![Screenshot_32](https://github.com/epam/edp-headlamp/assets/23012062/75721f33-7a37-4240-af5b-c426a60ed40e)
