### ISSUE TITLE
Add monitoring section into stage page

### ISSUE THREAD

**Issue by callmevladik** [epam/edp-headlamp#152]
Acceptance Criteria:

EDP Portal contain Grafana dashboard with valid metrics;
EDP Portal -> EDP -> Environments -> CD Pipeline -> CD Stages contain 'Monitoring' tab with Grafana Dashboard;
user must login to Grafana to see Dashboards;

https://dx-backstage-edp-delivery-backstage-dev.eks-sandbox.aws.main.edp.projects.epam.com/catalog/default/component/hk-java-maven/monitoring

**Comment by Serg1506** [comment]
![Screenshot_30](https://github.com/epam/edp-headlamp/assets/23012062/9867df5f-18a9-4dde-8174-13faddc4f46f)
![Screenshot_31](https://github.com/epam/edp-headlamp/assets/23012062/637722a6-2507-4a92-b2ab-da1af2832ff8)
