### ISSUE TITLE
Update cluster secret creation

### ISSUE THREAD

**Issue by callmevladik** [epam/edp-headlamp#161]
![image](https://github.com/epam/edp-headlamp/assets/42180137/1dc598cd-ca57-497a-b9f4-96f35cf69e3b)
![image](https://github.com/epam/edp-headlamp/assets/42180137/1c94df68-5b29-4561-8289-a118f6f92555)

**Comment by Serg1506** [comment]
![Screenshot_36](https://github.com/epam/edp-headlamp/assets/23012062/77dd610c-c86c-47b9-8ef5-00ac7f475e89)
