### ISSUE TITLE
Add available cbis tags for non-to-promote apps

### ISSUE THREAD

**Issue by callmevladik** [epam/edp-headlamp#174]

**Comment by Serg1506** [comment]
![Screenshot_47](https://github.com/epam/edp-headlamp/assets/23012062/3e8ea778-2e7d-4749-8ab9-9b3115935034)
![Screenshot_48](https://github.com/epam/edp-headlamp/assets/23012062/6ac22719-8bcd-4580-9679-833f5842ae53)
