### ISSUE TITLE
Update codebase flow

### ISSUE THREAD

**Issue by callmevladik** [epam/edp-headlamp#177]

**Comment by Serg1506** [comment]
![Screenshot_4](https://github.com/epam/edp-headlamp/assets/23012062/1505238b-82af-4126-8109-2f5efc301e44)
![Screenshot_5](https://github.com/epam/edp-headlamp/assets/23012062/3920d7d1-50d2-4f22-8d63-735547ab3b8b)
![Screenshot_6](https://github.com/epam/edp-headlamp/assets/23012062/8af7b533-7ab3-4361-b82f-824b9443bd7e)
![Screenshot_7](https://github.com/epam/edp-headlamp/assets/23012062/bbc66d7e-aca4-4d58-b421-f3469c11ab68)
