### ISSUE TITLE
Remove ability to create component with corrupt gitserver

### ISSUE THREAD

**Issue by callmevladik** [epam/edp-headlamp#179]

**Comment by Serg1506** [comment]
![Screenshot_24](https://github.com/epam/edp-headlamp/assets/23012062/550300ba-c3de-41a9-b826-ddeb4c44f065)
![Screenshot_25](https://github.com/epam/edp-headlamp/assets/23012062/5c028370-0c12-4b60-90e4-79fbe1d74abd)
![Screenshot_26](https://github.com/epam/edp-headlamp/assets/23012062/50fc2d39-acc8-4edc-a525-cefcf7a2dc6f)
