### ISSUE TITLE
Update requests error handling

### ISSUE THREAD

**Issue by callmevladik** [epam/edp-headlamp#183]

**Comment by Serg1506** [comment]
![Screenshot_37](https://github.com/epam/edp-headlamp/assets/23012062/addff124-17c3-4798-9b34-b17d769bcabe)
![Screenshot_38](https://github.com/epam/edp-headlamp/assets/23012062/832e6e89-007e-46e5-b532-d8bf47aa8311)
![Screenshot_34](https://github.com/epam/edp-headlamp/assets/23012062/5e69e4e1-063a-423e-90b9-808e60233fc8)
![Screenshot_35](https://github.com/epam/edp-headlamp/assets/23012062/cbdf6338-4395-4e1e-ac0e-86209ec93147)
![Screenshot_36](https://github.com/epam/edp-headlamp/assets/23012062/724b6d95-f7f1-4b9c-bafe-7c97aab04812)
