### ISSUE TITLE
Update cluster/general settings

### ISSUE THREAD

**Issue by callmevladik** [epam/edp-headlamp#189]

**Comment by Serg1506** [comment]
![Screenshot_42](https://github.com/epam/edp-headlamp/assets/23012062/1fd7c31a-6ff9-40a3-bc8a-52b775e313b7)
![Screenshot_43](https://github.com/epam/edp-headlamp/assets/23012062/92fbb9f8-f6b3-466a-89bd-608a607398d4)
![Screenshot_44](https://github.com/epam/edp-headlamp/assets/23012062/5e845b54-d5e1-4c8d-acb9-7c39827f3643)
