### ISSUE TITLE
Implement 'Pipelines' Tab with Real-time View of Pipeline Execution

### ISSUE THREAD

**Issue by SergK** [epam/edp-headlamp#205]
### **Is your feature request related to a problem? Please describe.**
Currently, the KubeRocketCI interface lacks a dedicated view for monitoring and managing PipelineRuns in real-time. Users need a more intuitive and accessible way to manage PipelineRuns, which includes deleting, re-triggering, and viewing logs for specific tasks within a PipelineRun.

### **Describe the solution you'd like**
Introduce a 'Pipelines' tab in the KubeRocketCI interface that provides a real-time view of Pipeline execution. This tab will allow users to:

- **Delete specific PipelineRuns:** Enhance user control by allowing deletion of runs.
- **Re-trigger PipelineRuns:** Offer the ability to re-trigger any completed or failed runs.
- **View Tasks and Logs:** Facilitate troubleshooting and monitoring by enabling access to task-specific logs.

### **Describe alternatives you've considered**
An alternative considered was to enhance the 'Pipelines' subsection on the Overview page. However, dedicating a separate tab for 'Pipelines' is more aligned with providing a focused and enriched user experience.

### **Additional context**
- The creation functionality present in the Tekton Dashboard for PipelineRuns is deemed not necessary for this iteration.
- Removing the Pipelines table from the Overview page and integrating it as a new section in the main menu is part of this feature's scope.
- The UI for the 'Pipelines' tab should be consistent with the overall look and feel of KubeRocketCI.

**Acceptance Criteria:**
- A 'Pipelines' tab is added to the UI, offering features to delete, re-trigger, and view logs for PipelineRuns.
- The UI design for the 'Pipelines' tab is consistent with the KubeRocketCI interface.
- Comprehensive testing (unit, integration, UI) is conducted to ensure feature reliability.
- Documentation for the 'Pipelines' tab is prepared and available to users.

**Implementation Plan:**
1. Design the UI/UX for the 'Pipelines' tab.
2. Implement the backend logic for managing PipelineRuns.
3. Develop the frontend integration for the 'Pipelines' tab.
4. Conduct thorough testing and validation.
5. Update the documentation to include the new 'Pipelines' tab features and usage.

**Screenshots:**

*labels*: `CodeMie`

**Comment by Serg1506** [comment]
![Screenshot_46](https://github.com/epam/edp-headlamp/assets/23012062/02f8de8a-3d03-4e17-9efd-6dedf96fffe7)
![Screenshot_48](https://github.com/epam/edp-headlamp/assets/23012062/60307d4e-021f-4789-a4cf-1bab81839917)
![Screenshot_51](https://github.com/epam/edp-headlamp/assets/23012062/cbace7c5-575b-4177-b7b7-255775deead1)
