### ISSUE TITLE
[FE] Apply the Menu Switcher

### ISSUE THREAD

**Issue by callmevladik** [epam/edp-headlamp#213]

**Comment by Serg1506** [comment]
![Screenshot_14](https://github.com/epam/edp-headlamp/assets/23012062/d3bf5a0b-f446-49c3-8702-63c294fa0a12)
![Screenshot_13](https://github.com/epam/edp-headlamp/assets/23012062/9e386ea9-138b-4aca-b92a-88cd2616329f)
