### ISSUE TITLE
Add pipelines page with real-time pipeline view

### ISSUE THREAD

**Issue by callmevladik** [epam/edp-headlamp#225]
As part of enhancing the KubeRocketCI user interface and functionality, it's proposed to introduce a dedicated 'Pipelines' tab. This tab will focus on providing a real-time view of Pipeline execution, mimicking the functionality found in the Tekton Dashboard's PipelineRuns page. The following capabilities are to be included:

Delete PipelineRun: Users should be able to delete specific PipelineRuns from the interface.
Re-trigger PipelineRun: There should be functionality to re-trigger any completed or failed PipelineRuns.
View Tasks and Logs: Users must be able to view specific tasks associated with a PipelineRun and access logs for these tasks.

Acceptance Criteria:
A new 'Pipelines' tab is successfully added to the KubeRocketCI interface.
From the 'Pipelines' tab, users can delete, re-trigger PipelineRuns, and view tasks and logs associated with a PipelineRun.
The 'Create' functionality for PipelineRuns, present in Tekton Dashboard, is not required to be implemented at this stage.
The UI and UX of the 'Pipelines' tab should be consistent with the rest of the KubeRocketCI interface.
Ensure thorough testing, including but not limited to unit tests, integration tests, and UI tests to validate the functionalities.
Implementation Plan:
Analyze the current implementation of the 'Pipelines' subsection on the Overview page.
Design the UI/UX for the new 'Pipelines' tab, ensuring consistency with the rest of the platform.
Implement the backend logic for deleting and re-triggering PipelineRuns.
Enable the feature to view tasks and access logs for each PipelineRun within the 'Pipelines' tab.
Conduct comprehensive testing across different scenarios to ensure robustness and reliability.
Prepare documentation for the new 'Pipelines' tab functionality, highlighting the key features and user instructions.

Useful:

Tekton Pipelines table - https://tekton-edp-delivery-tekton-dev.eks-sandbox.aws.main.edp.projects.epam.com/#/namespaces/edp-delivery-tekton-dev/pipelines
Current table in UI, pay attention to the Tree diagram, links, etc.
Remove the Pipelines table from the Overview page and add to the main manu as a new section

**Comment by Serg1506** [comment]
![Screenshot_51](https://github.com/epam/edp-headlamp/assets/23012062/0ef9690a-7d3a-49f7-89ca-90dc6cd77134)
![Screenshot_49](https://github.com/epam/edp-headlamp/assets/23012062/48718cd3-46a8-4a52-bae8-b6741e669096)
![Screenshot_50](https://github.com/epam/edp-headlamp/assets/23012062/2469f404-bc64-4c50-9e85-5b0913745fcf)
