### ISSUE TITLE
Add webhookUrl field into GitServer form

### ISSUE THREAD

**Issue by callmevladik** [epam/edp-headlamp#242]
In the Configuration Section of the Portal (under Configuration, GitServer), we need to implement a field for the Webhook URL that can be defined by the user. This enhancement should also include a comprehensive description clarifying that this field is optional. Our system will attempt to retrieve the webhook URL automatically via our codebase operator from the Ingress object. However, in scenarios where Ingress is not available, this field will enable users to manually specify their webhook URL. Additionally, we need to implement logic in the UI similar to that in the codebase-operator to potentially show users what the webhook URL is, even if it's auto-detected.

*Acceptance Criteria*:
1. A new Webhook URL field is implemented in the GitServer configuration section of the Portal.
2. The field includes a detailed description that explains its optional nature and its operational mechanism.
3. Logic is implemented in the UI to automatically obtain the webhook URL from the Ingress object, mirroring the functionality present in the codebase-operator.
4. The UI should be capable of displaying the detected webhook URL to the user, enhancing transparency and usability.
5. In the absence of an Ingress object, the system allows users to manually enter a Webhook URL.

https://github.com/epam/edp-tekton/blob/master/charts/pipelines-library/templates/resources/gitservers/gitserver.yaml#L18

**Comment by Serg1506** [comment]
![Screenshot_62](https://github.com/epam/edp-headlamp/assets/23012062/9b6f1e1d-6172-463c-8af4-a8b9b4480d35)
