### ISSUE TITLE
Deploy btn should be disabled when at least 1 item is not selected and its image tag is not chosen

### ISSUE THREAD

**Issue by callmevladik** [epam/edp-headlamp#245]

**Comment by Serg1506** [comment]
![Screenshot_58](https://github.com/epam/edp-headlamp/assets/23012062/a1c4e3ad-2c44-4420-a993-a99a0a8d3f25)
![Screenshot_59](https://github.com/epam/edp-headlamp/assets/23012062/81859c7b-9834-464d-a7c7-20ff0af011c2)
