### ISSUE TITLE
Add notifications on deploy/update/uninstall buttons click in applications section on stage page

### ISSUE THREAD

**Issue by callmevladik** [epam/edp-headlamp#37]

**Comment by Serg1506** [comment]
![Screenshot_16](https://github.com/epam/edp-headlamp/assets/23012062/4dcf9df9-a183-430e-b728-a191921c65e4)
![Screenshot_17](https://github.com/epam/edp-headlamp/assets/23012062/f1cd44e3-2016-4870-9526-ed8109cf7df4)
![Screenshot_19](https://github.com/epam/edp-headlamp/assets/23012062/b53a984f-7997-4f7b-b586-f5503b508beb)
