### ISSUE TITLE
Add link to values.yaml file from CD Stage in edp-gitops repo

### ISSUE THREAD

**Issue by callmevladik** [epam/edp-headlamp#38]
![image](https://github.com/epam/edp-headlamp/assets/42180137/ae3b0b13-fd7c-4ecc-b1a4-777b3ab26408)

For gitlab/github example:
https://git.epam.com/epmd-edp/sk-dev/edp-gitops/blob/main/demo/qa/goapp-values.yaml

https://git.epam.com/epmd-edp/sk-dev/edp-gitops/blob/main/<pipeline_name>/<stage_name>/<codeabase_name>-values.yaml

Or open just link to repo in main branch.

**Comment by Serg1506** [comment]
![Screenshot_17](https://github.com/epam/edp-headlamp/assets/23012062/12d87967-862e-4133-bb99-0c6455a2ed37)
