### ISSUE TITLE
Remove Hardcoded Pipeline Timeout in createBuildPipelineRunInstance Function

### ISSUE THREAD

**Issue by moonmanua** [epam/edp-headlamp#390]
### Description

**Problem Summary:**
The function `createBuildPipelineRunInstance` in the file `src/k8s/groups/Tekton/PipelineRun/utils/createBuildPipelineRunInstance/index.ts` contains a hardcoded value for the pipeline timeout at line 91. This should be replaced with a dynamic value that can be set based on the requirements.

**Steps to Reproduce:**
1. Open the file `src/k8s/groups/Tekton/PipelineRun/utils/createBuildPipelineRunInstance/index.ts`.
2. Navigate to line 91.
3. Observe the hardcoded timeout value.

**Expected Behavior:**
The pipeline timeout should be dynamically set based on the requirements, rather than being hardcoded.

**Actual Behavior:**
The pipeline timeout is hardcoded as `'1h0m0s'`.

**Screenshots / Code Snippet:**
```typescript
base.spec.timeouts = {
    pipeline: '1h0m0s',
};
```

### Environment
- **OS:** macOS Sonoma (aarch64)
- **IDE:** IntelliJ IDEA 2024.2.2, Ultimate Edition
- **JDK/SDK Version:** Java SDK version 19, Go SDK 1.22.5, Go programming language version 1.22

### Additional Information
To implement this change, the function should allow setting the pipeline timeout dynamically based on input parameters or configuration, ensuring flexibility and adaptability for different pipeline requirements.

**Comment by SergK** [comment]
Fixed in #400 through #401
Will be available as part of the platform 3.10.0 release
