### ISSUE TITLE
Align secrets fields in Platform UI configuration

### ISSUE THREAD

**Issue by callmevladik** [epam/edp-headlamp#42]
![image](https://github.com/epam/edp-headlamp/assets/42180137/5caf64fb-e75b-4bbe-b6a7-4ff869111ac1)

**Comment by Serg1506** [comment]
![Screenshot_5](https://github.com/epam/edp-headlamp/assets/23012062/22173773-8ea6-4d83-bd17-9603554e4ca6)
![Screenshot_20](https://github.com/epam/edp-headlamp/assets/23012062/6a6480af-bc6d-4b0f-8cdf-7686765c207d)
![Screenshot_6](https://github.com/epam/edp-headlamp/assets/23012062/450d3705-3abf-49ba-b74f-57fe739d581e)
![Screenshot_8](https://github.com/epam/edp-headlamp/assets/23012062/947c7f5b-65cc-454a-b020-23d7272b1c48)
![Screenshot_9](https://github.com/epam/edp-headlamp/assets/23012062/e3a643ed-93cf-43c5-8999-21e73ae3c3a4)
![Screenshot_10](https://github.com/epam/edp-headlamp/assets/23012062/dffd7926-8c1c-4e0f-8b05-12549dd426d0)
