### ISSUE TITLE
Refact configuration section

### ISSUE THREAD

**Issue by callmevladik** [epam/edp-headlamp#43]
Clarify description for gitops repository

Acceptance Criteria:

is case if something wrong use can understand potential reason from error message on gitops section;
status of gitOps repository available like in gitservers
git server - mandatory field in marketplace section (please add autofill and enable required flag);

**Comment by Serg1506** [comment]
![Screenshot_5](https://github.com/epam/edp-headlamp/assets/23012062/3db7d45c-d36d-414d-9463-455f442fae10)
![Screenshot_6](https://github.com/epam/edp-headlamp/assets/23012062/b16521aa-245a-49ca-a30b-8b4920d47da8)
![Screenshot_8](https://github.com/epam/edp-headlamp/assets/23012062/6e5bca84-3b23-432e-8a17-90f734d36298)
![Screenshot_9](https://github.com/epam/edp-headlamp/assets/23012062/257baf86-6044-4aa5-9b86-fb04631b146e)
