### ISSUE TITLE
Update GitServer provisioning

### ISSUE THREAD

**Issue by callmevladik** [epam/edp-headlamp#44]
Acceptance Criteria:

- git server can be presented only one;
- git server status can be seen;
- secret name - hardcode - ci-gitlab/github;
- gerrit - without modification;

**Comment by Serg1506** [comment]
![Screenshot_19](https://github.com/epam/edp-headlamp/assets/23012062/9a2d4abf-74e6-492a-aa0d-68a7a1db9ab9)
![Screenshot_11](https://github.com/epam/edp-headlamp/assets/23012062/d88e9498-6ef1-42ad-aa53-daab87ad97e0)
![Screenshot_12](https://github.com/epam/edp-headlamp/assets/23012062/9941914d-95e3-4d70-b1c6-31baf0bb5346)
