### ISSUE TITLE
Add ECR Registry into registry configuration

### ISSUE THREAD

**Issue by callmevladik** [epam/edp-headlamp#46]
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::093899590031:role/AWSIRSACoreSandboxEdpDeliveryKaniko

apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton
  annotations:
    eks.amazonaws.com/role-arn: <ARN_VALUE>

![image](https://github.com/epam/edp-headlamp/assets/42180137/c0509bb1-478e-4f72-a53d-4e01ea1f0843)

**Comment by Serg1506** [comment]
![Screenshot_6](https://github.com/epam/edp-headlamp/assets/23012062/3ea429df-964d-484e-bded-7ee5ce1f90d2)
