### ISSUE TITLE
Hide Create button for Component in case of git server do not exist

### ISSUE THREAD

**Issue by callmevladik** [epam/edp-headlamp#47]

**Comment by Serg1506** [comment]
![Screenshot_16](https://github.com/epam/edp-headlamp/assets/23012062/62e66dff-f650-4811-a454-648d346f9aab)
![Screenshot_17](https://github.com/epam/edp-headlamp/assets/23012062/47f91f5c-1dd1-4125-88fa-613a50fa64f9)
![Screenshot_18](https://github.com/epam/edp-headlamp/assets/23012062/98a6d21e-5600-46e5-9be2-3aa55e2a593b)
