### ISSUE TITLE
Git Server. Git Ops issues

### ISSUE THREAD

**Issue by callmevladik** [epam/edp-headlamp#49]
- fix git server creation(sshPort, httpsPort number type)
- fix crash on gitops page when there is no git server
- show no git servers message when there is no git server

**Comment by Serg1506** [comment]
![Screenshot_23](https://github.com/epam/edp-headlamp/assets/23012062/40302508-c131-44dd-abbf-b5a14a276e5c)
![Screenshot_24](https://github.com/epam/edp-headlamp/assets/23012062/b3b43cbf-2e66-4675-9eed-22d74a83f30d)
![Screenshot_25](https://github.com/epam/edp-headlamp/assets/23012062/c43d65e4-7754-4946-9307-bc908802299e)
