### ISSUE TITLE
Add logs viewer and terminal into stage applications deploy table columns

### ISSUE THREAD

**Issue by callmevladik** [epam/edp-headlamp#55]

**Comment by Serg1506** [comment]
![Screenshot_24](https://github.com/epam/edp-headlamp/assets/23012062/5d2a7ced-b5d1-4be3-bafb-3ef0daf3e828)
![Screenshot_25](https://github.com/epam/edp-headlamp/assets/23012062/fb637dea-d8b0-4061-8400-1c6e8abbd31e)
