### ISSUE TITLE
Add EDP Components (links) to overview page

### ISSUE THREAD

**Issue by callmevladik** [epam/edp-headlamp#69]
Acceptance Criteria:

EDP components (links) are available on overview page;
add edit button to redirect to configuration section for each component;

**Comment by Serg1506** [comment]
![Screenshot_5](https://github.com/epam/edp-headlamp/assets/23012062/cbbe6e0a-aba9-4d3d-82cc-423f020198a1)
![Screenshot_6](https://github.com/epam/edp-headlamp/assets/23012062/518c6374-d2f2-4305-801a-803cee61b604)
