### ISSUE TITLE
Fix overview page status filter

### ISSUE THREAD

**Issue by callmevladik** [epam/edp-headlamp#73]

**Comment by Serg1506** [comment]
![Screenshot_29](https://github.com/epam/edp-headlamp/assets/23012062/fc1c1ccc-7fd3-4dd1-8e82-307ed62fe7fc)
![Screenshot_30](https://github.com/epam/edp-headlamp/assets/23012062/9b8c509c-1afd-4dfb-8313-8034b4b70b57)
