### ISSUE TITLE
Update registry page

### ISSUE THREAD

**Issue by callmevladik** [epam/edp-headlamp#76]

**Comment by Serg1506** [comment]
![Screenshot_8](https://github.com/epam/edp-headlamp/assets/23012062/4bc7c52f-7ef7-4912-b60f-12d567ae0d7b)
![Screenshot_9](https://github.com/epam/edp-headlamp/assets/23012062/1cc65005-184a-4ad9-b61e-dfc26229ef2d)
![Screenshot_11](https://github.com/epam/edp-headlamp/assets/23012062/4add7acc-2ce2-4b77-bd52-359f946cdb1d)
![Screenshot_12](https://github.com/epam/edp-headlamp/assets/23012062/374a6601-bb40-4ad3-a991-615cf7aab507)
