### ISSUE TITLE
Add external links to application

### ISSUE THREAD

**Issue by callmevladik** [epam/edp-headlamp#77]
![image](https://github.com/epam/edp-headlamp/assets/42180137/b203dd05-f243-475a-9f63-20bdf6fb9e8a)

Acceptance Criteria:

EDP user can open ingress (external endpoint) from EDP Portal per application on stage;
Get ExternalURL from ArgoCD Application;

**Comment by Serg1506** [comment]
![Screenshot_6](https://github.com/epam/edp-headlamp/assets/23012062/78f4e426-691a-4ad6-bb7f-64004f8ce99e)
