### ISSUE TITLE
Add dependency track widget into codebasebranch section

### ISSUE THREAD

**Issue by callmevladik** [epam/edp-headlamp#79]
https://deptrack.eks-core.aws.main.edp.projects.epam.com/api/v1/badge/vulns/project/43e23418-30b9-4fdf-9a72-36b98d835e14

or use version pattern

https://docs.dependencytrack.org/integrations/badges/

Acceptance Criteria:

EDP Portal contain deptrack widget with project statistic;

**Comment by Serg1506** [comment]
![Screenshot_20](https://github.com/epam/edp-headlamp/assets/23012062/0d414b47-9aca-4fda-8519-1efb4711e341)
