### ISSUE TITLE
Forced branch version postfix (RC) on a Create new release form prevents to create release branches

### ISSUE THREAD

**Issue by n-g-work** [epam/edp-headlamp#9]
**Describe the bug**

The `Create new branch` form forces to fill the `branchVersionPostfix` field for release branches.
In previous EDP versions the use of the postfix was not enforced.

**EDP Versions**

EDP: v3.3.0
Tekton: v0.45.0
Headlamp image tag: 0.6.0

**Screenshots**

EDP v3.3.0 with Headlamp:
![image](https://github.com/epam/edp-headlamp/assets/101364051/3bd755fb-751e-41ad-b24f-f72debd2dafb)

EDP v2.12.1 with Admin Console:
![image](https://github.com/epam/edp-headlamp/assets/101364051/4c58e0c0-d4ac-40ea-8744-3a5ab2129519)

**Comment by alezander86** [comment]
@n-g-work EDP currently has two Versioning type strategies: "edp" and "default". In the "edp" strategy, we decided that the use of versioning is mandatory. However, based on your query, I understand that you don't want to render the versioning tag? In such a case, we may suggest that you use the "default" strategy or create your own custom versioning tagging.

**Comment by n-g-work** [comment]
Hi @alezander86,

There seems to be a misunderstanding. I **want** to use the `edp` versioning, but without the forced `RC` postfix in a release version.

Currently the EDP Headlamp UI forces to create a new release branch with this postfix, and I have to manually alter the Codebase Branch custom resource to remove the `RC` after it is created.

To fix this bug I suggest to remove the `required` validation on the `branchVersionPostfix` field of the `Create new branch` form:
https://github.com/epam/edp-headlamp/blob/7500b79138b38cd98ef1b85c34ad529817d6dbc1/src/components/FormFields/CodebaseBranchFields/BranchVersion/index.tsx#L102

**Comment by alezander86** [comment]
We have acknowledged and implemented your idea. The "branchVersionPostfix" field is no longer mandatory when creating release branches. Users can now leave it empty if they prefer. This feature will be included in the next release of EDP.

We appreciate your feedback and active participation in improving our product. If you have any further suggestions or questions, please don't hesitate to reach out to us. We are always ready to help and enhance our system based on the needs of our users.
![Screenshot_49](https://github.com/epam/edp-headlamp/assets/77995538/ce53797c-321e-4db6-95ab-458e773cdaff)
